# generated by datamodel-codegen:
#   filename:  definitions.json
#   timestamp: 2024-09-22T12:23:03+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Model(BaseModel):
    pass


class Guid(RootModel[UUID]):
    root: UUID = Field(
        ...,
        description='A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.',
    )


class GDLParameterDetails(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    index: str = Field(..., description='The index of the parameter.')
    type: str = Field(..., description='The type of the parameter.')
    dimension1: Optional[float] = Field(
        None, description='The 1st dimension of array (in case of array value).'
    )
    dimension2: Optional[float] = Field(
        None, description='The 2nd dimension of array (in case of array value).'
    )
    value: Any = Field(..., description='The value of the parameter.')


class Field2DCoordinate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float = Field(..., description='X value of the coordinate.')
    y: float = Field(..., description='Y value of the coordinate.')


class Field3DCoordinate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float = Field(..., description='X value of the coordinate.')
    y: float = Field(..., description='Y value of the coordinate.')
    z: float = Field(..., description='Z value of the coordinate.')


class Field3DDimensions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float = Field(..., description='X dimension.')
    y: float = Field(..., description='Y dimension.')
    z: float = Field(..., description='Z dimension.')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: int = Field(..., description='The code of the error.')
    message: str = Field(..., description='The error message.')


class ErrorItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Error


class Success(Enum):
    boolean_True = True


class SuccessfulExecutionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Success


class Success1(Enum):
    boolean_False = False


class FailedExecutionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: Success1
    error: Error = Field(..., description='The details of an execution failure.')


class ExecutionResult(
    RootModel[Union[SuccessfulExecutionResult, FailedExecutionResult]]
):
    root: Union[SuccessfulExecutionResult, FailedExecutionResult] = Field(
        ..., description='The result of the execution.'
    )


class ExecutionResults(RootModel[List[ExecutionResult]]):
    root: List[ExecutionResult] = Field(..., description='A list of execution results.')


class ElementType(Enum):
    Wall = 'Wall'
    Column = 'Column'
    Beam = 'Beam'
    Window = 'Window'
    Door = 'Door'
    Object = 'Object'
    Lamp = 'Lamp'
    Slab = 'Slab'
    Roof = 'Roof'
    Mesh = 'Mesh'
    Dimension = 'Dimension'
    RadialDimension = 'RadialDimension'
    LevelDimension = 'LevelDimension'
    AngleDimension = 'AngleDimension'
    Text = 'Text'
    Label = 'Label'
    Zone = 'Zone'
    Hatch = 'Hatch'
    Line = 'Line'
    PolyLine = 'PolyLine'
    Arc = 'Arc'
    Circle = 'Circle'
    Spline = 'Spline'
    Hotspot = 'Hotspot'
    CutPlane = 'CutPlane'
    Camera = 'Camera'
    CamSet = 'CamSet'
    Group = 'Group'
    SectElem = 'SectElem'
    Drawing = 'Drawing'
    Picture = 'Picture'
    Detail = 'Detail'
    Elevation = 'Elevation'
    InteriorElevation = 'InteriorElevation'
    Worksheet = 'Worksheet'
    Hotlink = 'Hotlink'
    CurtainWall = 'CurtainWall'
    CurtainWallSegment = 'CurtainWallSegment'
    CurtainWallFrame = 'CurtainWallFrame'
    CurtainWallPanel = 'CurtainWallPanel'
    CurtainWallJunction = 'CurtainWallJunction'
    CurtainWallAccessory = 'CurtainWallAccessory'
    Shell = 'Shell'
    Skylight = 'Skylight'
    Morph = 'Morph'
    ChangeMarker = 'ChangeMarker'
    Stair = 'Stair'
    Riser = 'Riser'
    Tread = 'Tread'
    StairStructure = 'StairStructure'
    Railing = 'Railing'
    RailingToprail = 'RailingToprail'
    RailingHandrail = 'RailingHandrail'
    RailingRail = 'RailingRail'
    RailingPost = 'RailingPost'
    RailingInnerPost = 'RailingInnerPost'
    RailingBaluster = 'RailingBaluster'
    RailingPanel = 'RailingPanel'
    RailingSegment = 'RailingSegment'
    RailingNode = 'RailingNode'
    RailingBalusterSet = 'RailingBalusterSet'
    RailingPattern = 'RailingPattern'
    RailingToprailEnd = 'RailingToprailEnd'
    RailingHandrailEnd = 'RailingHandrailEnd'
    RailingRailEnd = 'RailingRailEnd'
    RailingToprailConnection = 'RailingToprailConnection'
    RailingHandrailConnection = 'RailingHandrailConnection'
    RailingRailConnection = 'RailingRailConnection'
    RailingEndFinish = 'RailingEndFinish'
    BeamSegment = 'BeamSegment'
    ColumnSegment = 'ColumnSegment'
    Opening = 'Opening'
    Unknown = 'Unknown'


class ElementFilter(Enum):
    IsEditable = 'IsEditable'
    IsVisibleByLayer = 'IsVisibleByLayer'
    IsVisibleByRenovation = 'IsVisibleByRenovation'
    IsVisibleByStructureDisplay = 'IsVisibleByStructureDisplay'
    IsVisibleIn3D = 'IsVisibleIn3D'
    OnActualFloor = 'OnActualFloor'
    OnActualLayout = 'OnActualLayout'
    InMyWorkspace = 'InMyWorkspace'
    IsIndependent = 'IsIndependent'
    InCroppedView = 'InCroppedView'
    HasAccessRight = 'HasAccessRight'
    IsOverriddenByRenovation = 'IsOverriddenByRenovation'


class WindowType(Enum):
    FloorPlan = 'FloorPlan'
    Section = 'Section'
    Details = 'Details'
    field_3DModel = '3DModel'
    Layout = 'Layout'
    Drawing = 'Drawing'
    CustomText = 'CustomText'
    CustomDraw = 'CustomDraw'
    MasterLayout = 'MasterLayout'
    Elevation = 'Elevation'
    InteriorElevation = 'InteriorElevation'
    Worksheet = 'Worksheet'
    Report = 'Report'
    field_3DDocument = '3DDocument'
    External3D = 'External3D'
    Movie3D = 'Movie3D'
    MovieRendering = 'MovieRendering'
    Rendering = 'Rendering'
    ModelCompare = 'ModelCompare'
    Interactive_Schedule = 'Interactive Schedule'
    Unknown = 'Unknown'


class IssueId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    guid: Guid


class IssueIdArrayItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    issueId: IssueId


class Issues(RootModel[List[IssueIdArrayItem]]):
    root: List[IssueIdArrayItem] = Field(..., description='A list of Issues.')


class IssueElementType(Enum):
    Creation = 'Creation'
    Highlight = 'Highlight'
    Deletion = 'Deletion'
    Modification = 'Modification'


class IssueCommentStatus(Enum):
    Error = 'Error'
    Warning = 'Warning'
    Info = 'Info'
    Unknown = 'Unknown'


class PropertyId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    guid: Guid


class PropertyIdArrayItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    propertyId: PropertyId


class PropertyIds(RootModel[List[PropertyIdArrayItem]]):
    root: List[PropertyIdArrayItem] = Field(
        ..., description='A list of property identifiers.'
    )


class PropertyValue(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value: str


class PropertyValueOrErrorItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    propertyValue: PropertyValue


class PropertyValueOrErrorItem(RootModel[Union[PropertyValueOrErrorItem1, ErrorItem]]):
    root: Union[PropertyValueOrErrorItem1, ErrorItem] = Field(
        ..., description='A property value or an error'
    )


class PropertyValues(RootModel[List[PropertyValueOrErrorItem]]):
    root: List[PropertyValueOrErrorItem] = Field(
        ..., description='A list of property values.'
    )


class PropertyValuesOrError1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    propertyValues: PropertyValues


class PropertyValuesOrError(RootModel[Union[PropertyValuesOrError1, ErrorItem]]):
    root: Union[PropertyValuesOrError1, ErrorItem] = Field(
        ..., description='A list of property values or an error.'
    )


class PropertyValuesOrErrorArray(RootModel[List[PropertyValuesOrError]]):
    root: List[PropertyValuesOrError] = Field(
        ..., description='A list of property value lists.'
    )


class ClassificationSystemId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    guid: Guid


class ClassificationSystemIdArrayItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    classificationSystemId: ClassificationSystemId


class ClassificationSystemIds(RootModel[List[ClassificationSystemIdArrayItem]]):
    root: List[ClassificationSystemIdArrayItem] = Field(
        ..., description='A list of classification system identifiers.'
    )


class ClassificationItemId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    guid: Guid


class ClassificationId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    classificationSystemId: ClassificationSystemId
    classificationItemId: Optional[ClassificationItemId] = Field(
        None,
        description="The element's classification in the given system. If no value is specified here, the element is Unclassified in this system.",
    )


class ClassificationIdOrError1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    classificationId: ClassificationId


class ClassificationIdOrError(RootModel[Union[ClassificationIdOrError1, ErrorItem]]):
    root: Union[ClassificationIdOrError1, ErrorItem] = Field(
        ..., description='A classification identifier or an error.'
    )


class ClassificationIdsOrErrors(RootModel[List[ClassificationIdOrError]]):
    root: List[ClassificationIdOrError] = Field(
        ..., description='A list of element classification identifiers or errors.'
    )


class ElementClassificationOrError1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    classificationIds: ClassificationIdsOrErrors


class ElementClassificationOrError(
    RootModel[Union[ElementClassificationOrError1, ErrorItem]]
):
    root: Union[ElementClassificationOrError1, ErrorItem] = Field(
        ..., description='Element classification identifiers or errors.'
    )


class ElementClassificationsOrErrors(RootModel[List[ElementClassificationOrError]]):
    root: List[ElementClassificationOrError] = Field(
        ..., description='A list of element classification identifiers or errors.'
    )


class ElementId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    guid: Guid


class AttributeId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    guid: Guid


class GDLParametersDictionary(RootModel[Optional[Dict[str, GDLParameterDetails]]]):
    root: Optional[Dict[str, GDLParameterDetails]] = None


class ElementPropertyValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    elementId: ElementId
    propertyId: PropertyId
    propertyValue: PropertyValue


class ElementPropertyValues(RootModel[List[ElementPropertyValue]]):
    root: List[ElementPropertyValue] = Field(
        ..., description='A list of element property values.'
    )


class ElementClassification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    elementId: ElementId
    classificationId: ClassificationId


class ElementClassifications(RootModel[List[ElementClassification]]):
    root: List[ElementClassification] = Field(
        ..., description='A list of element classification identifiers.'
    )


class ElementIdArrayItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    elementId: ElementId


class AttributeIdArrayItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attributeId: AttributeId


class Elements(RootModel[List[ElementIdArrayItem]]):
    root: List[ElementIdArrayItem] = Field(..., description='A list of elements.')


class AttributeIds(RootModel[List[AttributeIdArrayItem]]):
    root: List[AttributeIdArrayItem] = Field(..., description='A list of attributes.')


class Hotlink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    location: str = Field(..., description='The path of the hotlink file.')
    children: Optional[Hotlinks] = Field(
        None, description='The children of the hotlink node if it has any.'
    )

class Hotlinks(RootModel[List[Hotlink]]):
    root: List[Hotlink] = Field(..., description='A list of hotlink nodes.')





Hotlinks.model_rebuild()
